### Запись тест кейса
POST http://localhost:8080/autotest/record/start/
Content-Type: application/json

{
  "testCaseName": "test1",
  "folderName":"folder",
  "url": "https://www.google.ru/",
  "host": "http://localhost:8090"
}

### Стоп записи теста
GET http://localhost:8080/autotest/record/stop

### Выход из записи теста
POST http://localhost:8080/autotest/record/exit

###