// Запись тест кейса
POST http://localhost:8080/autotest/record/start/
Content-Type: application/json

{
  "pathToApp": "/Applications/Google Chrome.app",
  "testCaseName": "test",
  "url": "file:///Users/sergejstahanov/Desktop/robotProject/robot_test/index.html"
}

###


// Старт записи скриншота
POST http://localhost:8080/autotest/screenshot/start
Content-Type: application/json

{
  "x": 0,
  "y": 0,
  "width": 1920,
  "height": 1080
}

###

// Стоп записи скриншота
POST http://localhost:8080/autotest/screenshot/stop

###

// Стоп записи теста
GET http://localhost:8080/autotest/record/stop

###

// Старт робота
POST http://localhost:8080/autotest/robot/start
Content-Type: application/json

{
  "testCase": "test1"
}

###

// Выгрузка тест-кейсов
GET http://localhost:8080/autotest/robot/getAll

###

// Удалить тест-кейс
POST http://localhost:8080/autotest/robot/delete
Content-Type: application/json

{
  "testCase": "test1"
}

###
