// Проверяем запущено ли приложение
GET http://localhost:8080/autotest/ping/

###

// Получить текущий уровень логгирования
GET http://localhost:8080/autotest/actuator/loggers/ru.sertok.robot

###

// Изменить уровень логгирования
POST http://localhost:8080/autotest/actuator/loggers/ru.sertok.robot
Content-Type: application/json

{
  "configuredLevel": "debug"
}

###

// Путь до запускаемого приложения
POST http://localhost:8080/autotest/settings/pathToApp/
Content-Type: application/json

{
  "pathToApp": "/Applications/Google Chrome.app"
}

###

// Путь до запускаемого приложения
POST http://localhost:8080/autotest/record/start/
Content-Type: application/json

{
  "testCaseName": "test",
  "url": "file:///Users/sergejstahanov/Desktop/robot_test/index.html"
}

###


// Старт записи скриншота
POST http://localhost:8080/autotest/screenshot/start
Content-Type: application/json

{
  "x": 0,
  "y": 0,
  "width": 1920,
  "height": 1080
}

###

// Стоп записи скриншота
POST http://localhost:8080/autotest/screenshot/stop

###

// Стоп записи скриншота
POST http://localhost:8080/autotest/record/stop

###