### Старт робота
POST http://localhost:8080/autotest/robot/start
Content-Type: application/json

{
  "testCase": "test2"
}

### Выгрузка тест-кейсов
GET http://localhost:8080/autotest/robot/getAll

### Выгрузка папок
GET http://localhost:8080/autotest/robot/getFolders

### Выгрузить тест
GET http://localhost:8080/autotest/robot/get/test

### Удалить тест-кейс
POST http://localhost:8080/autotest/robot/delete
Content-Type: application/json

{
  "testCase": "test"
}

###