### Старт записи скриншота
POST http://localhost:8080/autotest/screenshot/start
Content-Type: application/json

{
  "size": {
    "x": 500,
    "y": 500,
    "width": 500,
    "height": 500
  }
}

### Стоп записи скриншота
POST http://localhost:8080/autotest/screenshot/stop

### Нажатие на кнопку crop
POST http://localhost:8080/autotest/screenshot/crop

###
